image: null

variables:
  # This will suppress any download for dependencies and plugins or upload messages which would clutter the console log.
  # `showDateTime` will show the passed time in milliseconds. You need to specify `--batch-mode` to make this work.
  MAVEN_OPTS: |
    -Dhttps.protocols=TLSv1.2
    -Dorg.slf4j.simpleLogger.showDateTime=true
    -Djava.awt.headless=true
    -XX:+UseParallelOldGC
  # As of Maven 3.3.0 instead of this you may define these options in `.mvn/maven.config` so the same config is used
  # when running from the command line.
  # `installAtEnd` and `deployAtEnd` are only effective with recent version of the corresponding plugins.
  MAVEN_CLI_OPTS: |
    -f stackgres-k8s/src/pom.xml
    --batch-mode
    --errors
    --fail-at-end
    --show-version
    -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository
    -DinstallAtEnd=true
    -DdeployAtEnd=true
    -Dsurefire.useFile=false
    -Dsurefire.useFile=false
    -DtrimStackTrace=false
  E2E_ENV: kind
  E2E_PARALLELISM: 32
  K8S_VERSION: 1.15.11
  K8S_FROM_DIND: "true"
  K8S_REUSE: "true"
  DOCUMENTATION_BASE_URL: "https://ongresinc.gitlab.io/web/stackgres/doc/latest"
  PRODUCTION_DOCUMENTATION_BASE_URL: "https://stackgres.io/doc/latest"
  SKIP_NATIVE: "false"
  SKIP_E2E: "false"
  SKIP_DEPLOY: "false"

# Cache downloaded dependencies and plugins between builds.
# To keep cache across branches add 'key: "$CI_JOB_NAME"'
cache:
  paths:
    - .m2/repository

stages:
  - build
  - native build
  - image build
  - test
  - check-release
  - deploy

include:
  - local: .gitlab-ci/build.yml
  - local: .gitlab-ci/native-build.yml
  - local: .gitlab-ci/image-build.yml
  - local: .gitlab-ci/test.yml
  - local: .gitlab-ci/check-release.yml
  - local: .gitlab-ci/deploy.yml
