image: null

variables:
  GRAALVM_IMAGE: docker.io/ongres/ubi-graalvm-maven:21.0.0.2-java11
  # This will suppress any download for dependencies and plugins or upload messages which would clutter the console log.
  # `showDateTime` will show the passed time in milliseconds. You need to specify `--batch-mode` to make this work.
  MAVEN_OPTS: |
    -Djdk.tls.client.protocols=TLSv1.2
    -Dhttps.protocols=TLSv1.2
    -Dorg.slf4j.simpleLogger.showDateTime=true
    -Djava.awt.headless=true
    -XX:+UseParallelGC
  # As of Maven 3.3.0 instead of this you may define these options in `.mvn/maven.config` so the same config is used
  # when running from the command line.
  # `installAtEnd` and `deployAtEnd` are only effective with recent version of the corresponding plugins.
  MAVEN_CLI_OPTS: |
    -f stackgres-k8s/src/pom.xml
    --batch-mode
    --errors
    --fail-at-end
    --show-version
    --no-transfer-progress
    -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository
    -Dmaven.user.home=$CI_PROJECT_DIR/.m2
    -DinstallAtEnd=true
    -DdeployAtEnd=true
    -Dsurefire.useFile=false
    -DtrimStackTrace=false
  SKIP_NATIVE: "false"
  SKIP_E2E: "false"
  SKIP_DEPLOY: "false"
  E2E_SHELL: sh
  E2E_ENV: kind
  E2E_PARALLELISM: 32
  E2E_JOBS: 3
  E2E_EXCLUSIVE_JOBS: 3
  K8S_VERSION: 1.16.15
  K8S_FROM_DIND: "true"
  K8S_REUSE: "true"
  SG_CURRENT_VERSION: "1.0"

workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS'
      when: never
    - if: '$CI_COMMIT_BRANCH'

# Cache downloaded dependencies and plugins between builds.
# To keep cache across branches add 'key: "$CI_JOB_NAME"'
cache: &global_cache
  paths:
    - .m2
  policy: pull-push

stages:
  - build
  - post-build
  - native build
  - image build
  - test
  - documentation
  - deploy

include:
  - local: .gitlab-ci/build.yml
  - local: .gitlab-ci/post-build.yml
  - local: .gitlab-ci/native-build.yml
  - local: .gitlab-ci/image-build.yml
  - local: .gitlab-ci/test.yml
  - local: .gitlab-ci/check-release.yml
  - local: .gitlab-ci/deploy.yml
  - local: .gitlab-ci/documentation.yml
