image: null

variables:
<<<<<<< HEAD
  SG_CI_IMAGE_NAME: "ci:1.13"
=======
  SG_CI_IMAGE_NAME: "ci:1.14"
>>>>>>> 2a1d1559d (ci: support for kind 0.14.0)
  BUILDER_IMAGE_NAME: "builder:1.4"
  SKIP_NATIVE: "false"
  SKIP_E2E: "false"
  SKIP_DEPLOY: "false"
  E2E_JOBS: 3
  E2E_EXCLUSIVE_JOBS: 3
  E2E_RETRY: 2
  E2E_FAILURE_RETRY: 3
  ARTIFACT_DOWNLOAD_ATTEMPTS: 3
  EXECUTOR_JOB_SECTION_ATTEMPTS: 3
  GET_SOURCES_ATTEMPTS: 3
  RESTORE_CACHE_ATTEMPTS: 3
  E2E_SHELL: sh
  E2E_ENV: kind
  K8S_VERSION: 1.18.20
  LATEST: "false"

stages:
  - pre build
  - pre build multi archs
  - build 1
  - build 2
  - image build
  - image build multi archs
  - test
  - deploy

include:
  - local: .gitlab-ci/pre-build.yml
  - local: .gitlab-ci/build.yml
  - local: .gitlab-ci/native-build.yml
  - local: .gitlab-ci/image-build.yml
  - local: .gitlab-ci/test.yml
  - local: .gitlab-ci/e2e-test.yml
  - local: .gitlab-ci/deploy.yml
