paths:
  /stackgres/applications:
    get:
      tags:
      - applications
      summary: List StackGres applications
      description: |
        List of the available StackGres applications.

        ### RBAC permissions required

        None
      security:
      - JWT: []
  /stackgres/applications/{publisher}/{name}:
    get:
      tags:
      - applications
      summary: Get StackGres application
      description: |
        Get a StackGres application info.

        ### RBAC permissions required

        None
      parameters:
      - name: publisher
        description: The publisher of the application to retrieve
        in: path
        required: true
        schema:
          type: string
      - name: name
        description: The name of the application to retrieve
        in: path
        required: true
        schema:
          type: string
      security:
      - JWT: []
  /stackgres/applications/com.ongres/babelfish-compass:
    post:
      tags:
      - applications
      summary: Run Babelfish Compass application
      description: |
        Run Babelfish Compass application.

        The payload must be a valid MS SQL Server script that will be checked by [Babelfish Compass](https://github.com/babelfish-for-postgresql/babelfish_compass).

        ### RBAC permissions required

        * jobs create, delete
        * pods list, get
        * pods/exec create 
      security:
      - JWT: []
        