paths:
  /stackgres/sgbackupconfigs:
    get:
      tags:
      - sgbackupconfig
      summary: List sgbackupconfigs
      description: |
        List sgbackupconfigs and read values from the referenced secrets.

        ### RBAC permissions required

        * sgbackupconfigs list
        * secrets get
      security:
      - JWT: []
    put:
      tags:
      - sgbackupconfig
      summary: Update a sgbackupconfig
      description: |
        Update a sgbackupconfig.
         If values are provided referenced secrets are created/patched or a secret named as
         the sgbackupconfig with `-secrets` suffix is created/patched if no secret is
         referenced.

        ### RBAC permissions required

        * sgbackupconfigs patch
        * secrets get, create, patch
      security:
      - JWT: []
    post:
      tags:
      - sgbackupconfig
      summary: Create a sgbackupconfig
      description: |
        Create a sgbackupconfig.
         If values are provided referenced secrets are created/patched or a secret named as
         the sgbackupconfig with `-secrets` suffix is created/patched if no secret is
         referenced.

        ### RBAC permissions required

        * sgbackupconfigs create
        * secrets get, create, patch
      security:
      - JWT: []
    delete:
      tags:
      - sgbackupconfig
      summary: Delete a sgbackupconfig
      description: |
        Delete a sgbackupconfig.
         If a secret named as the sgbackupconfig with `-secrets` suffix is found, it will be
         deleted also.


        ### RBAC permissions required

        * sgbackupconfigs delete
        * secrets get, delete
      security:
      - JWT: []
  /stackgres/{namespace}/sgbackupconfigs/{name}:
    get:
      tags:
      - sgbackupconfig
      summary: Get a sgbackupconfig
      description: |
        Get a sgbackupconfig and read values from the referenced secrets.

        ### RBAC permissions required

        * sgbackupconfigs get
        * secrets get
      parameters:
      - name: namespace
        description: The namespace to retrieve the resource from
        in: path
        required: true
        schema:
          type: string
      - name: name
        description: The name of the resource to retrieve
        in: path
        required: true
        schema:
          type: string
      security:
      - JWT: []
