paths:
  /stackgres/sgobjectstorages:
    get:
      tags:
        - sgconfig
      summary: List sgconfigs
      description: |
        List sgconfigs and read values from the referenced secrets.

        ### RBAC permissions required

        * sgconfigs list
      security:
      - JWT: []
    put:
      tags:
        - sgconfig
      summary: Update a sgconfigs
      description: |
        Update a sgconfigs.

        ### RBAC permissions required

        * sgconfigs patch
      security:
      - JWT: []
    post:
      tags:
        - sgconfig
      summary: Create a sgconfigs
      description: |
        Create a sgconfigs.

        ### RBAC permissions required

        * sgobjectstorages create
      security:
      - JWT: []
    delete:
      tags:
        - sgconfig
      summary: Delete a sgconfigs
      description: |
        Delete a sgconfigs.

        ### RBAC permissions required

        * sgconfigs delete
      security:
      - JWT: []
  /stackgres/namespaces/{namespace}/sgconfigs/{name}:
    get:
      tags:
        - sgconfig
      summary: Get a sgconfigs
      description: |
        Get a sgconfigs.

        ### RBAC permissions required

        * sgobjectstorages get
      parameters:
        - name: namespace
          description: The namespace to retrieve the resource from
          in: path
          required: true
          schema:
            type: string
        - name: name
          description: The name of the resource to retrieve
          in: path
          required: true
          schema:
            type: string
      security:
        - JWT: []
