paths:
  /stackgres/sgpoolconfigs:
    get:
      tags:
      - sgpoolconfig
      summary: List sgpoolconfigs
      description: |
        List sgpoolconfigs.

        ### RBAC permissions required

        * sgpoolconfigs list
      security:
      - JWT: []
    put:
      tags:
      - sgpoolconfig
      summary: Update a sgpoolconfig
      description: |
        Update a sgpoolconfig.

        ### RBAC permissions required

        * sgpoolconfig patch
      security:
      - JWT: []
    post:
      tags:
      - sgpoolconfig
      summary: Create a sgpoolconfig
      description: |
        Create a sgpoolconfig.

        ### RBAC permissions required

        * sgpoolconfig create
      security:
      - JWT: []
    delete:
      tags:
      - sgpoolconfig
      summary: Delete a sgpoolconfig
      description: |
        Delete a sgpoolconfig.

        ### RBAC permissions required

        * sgpoolconfig delete
      security:
      - JWT: []
  /stackgres/namespaces/{namespace}/sgpoolconfigs/{name}:
    get:
      tags:
      - sgpoolconfig
      summary: Get a sgpoolconfig
      description: |
        Get a sgpoolconfig.

        ### RBAC permissions required

        * sgpoolconfig get
      parameters:
      - name: namespace
        description: The namespace to retrieve the resource from
        in: path
        required: true
        schema:
          type: string
      - name: name
        description: The name of the resource to retrieve
        in: path
        required: true
        schema:
          type: string
      security:
      - JWT: []
