paths:
  /stackgres/sgpgconfigs:
    get:
      tags:
      - sgpgconfig
      summary: List sgpgconfigs
      description: |
        List sgpgconfigs.

        ### RBAC permissions required

        * sgpgconfigs list
      security:
      - JWT: []
    put:
      tags:
      - sgpgconfig
      summary: Update a sgpgconfig
      description: |
        Update a sgpgconfig.

        ### RBAC permissions required

        * sgpgconfigs patch
      security:
      - JWT: []
    post:
      tags:
      - sgpgconfig
      summary: Create a sgpgconfig
      description: |
        Create a sgpgconfig.

        ### RBAC permissions required

        * sgpgconfigs create
      security:
      - JWT: []
    delete:
      tags:
      - sgpgconfig
      summary: Delete a sgpgconfig
      description: |
        Delete a sgpgconfig.

        ### RBAC permissions required

        * sgpgconfigs delete
      security:
      - JWT: []
  /stackgres/namespaces/{namespace}/sgpgconfigs/{name}:
    get:
      tags:
      - sgpgconfig
      summary: Get a sgpgconfig
      description: |
        Get a sgpgconfig.

        ### RBAC permissions required

        * sgpgconfigs get
      parameters:
      - name: namespace
        description: The namespace to retrieve the resource from
        in: path
        required: true
        schema:
          type: string
      - name: name
        description: The name of the resource to retrieve
        in: path
        required: true
        schema:
          type: string
      security:
      - JWT: []
