configurations:
  postgresconfig:
    postgresql.conf:
      shared_buffers: '32MB'
  backupconfig:
    create: false
cluster:
  postgres:
    version: "13"
  pods:
    persistentVolume:
      size: 128Mi
  configurations:
    sgBackupConfig: null
  prometheusAutobind: false
  managedSql:
    scripts:
      - script: 'CREATE EXTENSION pg_repack'
  postgres:
    extensions:
      - name: pg_repack
nonProductionOptions:
  disableClusterPodAntiAffinity: true
