configurations:
  postgresconfig:
    postgresql.conf:
      shared_buffers: '32MB'
  backupconfig:
    create: false
cluster:
  pods:
    persistentVolume:
      size: 128Mi
  configurations:
    sgBackupConfig: null
  prometheusAutobind: true
nonProductionOptions:
  disableClusterPodAntiAffinity: true
