configurations:
  postgresconfig:
    postgresql.conf:
      shared_buffers: '32MB'
  backupconfig:
    create: false
cluster:
  postgres:
    version: "13"
  pods:
    persistentVolume:
      size: 128Mi
  configurations:
    sgBackupConfig: null
  managedSql:
    scripts:
    - name: create-sakila-user
      scriptFrom:
        secretKeyRef: # read the user from a Secret to maintain credentials in a safe place
          name: sql-scripts-sakila-user
          key: create-sakila-user.sql
    - name: create-sakila-database
      script: |
        CREATE DATABASE sakila WITH OWNER sakila;
    - database: sakila
      scriptFrom:
        configMapKeyRef: # read long script from a ConfigMap to avoid have to much data in the helm releasea and the sgcluster CR
          name: sql-scripts-sakila-schema
          key: create-sakila-schema.sql
  prometheusAutobind: false
nonProductionOptions:
  disableClusterPodAntiAffinity: true
