configurations:
  postgresconfig:
    postgresql.conf:
      shared_buffers: '32MB'
  backupconfig:
    create: true
    # Avoid automatic backups
    baseBackups:
      retention: 2
      cronSchedule: '0 5 31 2 *'
cluster:
  postgres:
    version: "13"
  pods:
    persistentVolume:
      size: 128Mi
  configurations:
    sgBackupConfig: backupconf
  prometheusAutobind: true
distributedLogs:
  enabled: true
nonProductionOptions:
  disableClusterPodAntiAffinity: true
