{{ if and (eq .Values.kind "SGShardedCluster") .Values.cluster.create }}
apiVersion: stackgres.io/v1alpha1
kind: SGShardedCluster
metadata:
  name: {{ .Release.Name }}
  {{- if .Values.cluster.version }}
  annotations:
    stackgres.io/operatorVersion: "{{ .Values.cluster.version }}"
  {{- end }}
spec:
  type: {{ .Values.shardedCluster.type }}
  database: {{ .Values.shardedCluster.database }}
  postgres:
    version: '{{ .Values.cluster.postgres.version }}'
  coordinator:
    instances: {{ .Values.cluster.instances }}
    configurations: 
      sgPostgresConfig: '{{ .Values.cluster.configurations.sgPostgresConfig }}'
      sgPoolingConfig: '{{ .Values.cluster.configurations.sgPoolingConfig }}'
    sgInstanceProfile: '{{ .Values.cluster.sgInstanceProfile }}'
    pods:
      persistentVolume:
        size: '{{ .Values.cluster.pods.persistentVolume.size }}'
        {{- if .Values.cluster.pods.persistentVolume.storageClass }}
        {{- if eq "-" .Values.cluster.pods.persistentVolume.storageClass }}
        storageClass: ""
        {{- else }}
        storageClass: {{ .Values.cluster.pods.persistentVolume.storageClass }}
        {{- end }}
        {{- end }}
  shards:
    clusters: {{ .Values.shardedCluster.shards.clusters }}
    instancesPerCluster: {{ .Values.shardedCluster.shards.instancesPerCluster }}
    configurations: 
      sgPostgresConfig: '{{ .Values.cluster.configurations.sgPostgresConfig }}'
      sgPoolingConfig: '{{ .Values.cluster.configurations.sgPoolingConfig }}'
    sgInstanceProfile: '{{ .Values.cluster.sgInstanceProfile }}'
    pods:
      persistentVolume:
        size: '{{ .Values.cluster.pods.persistentVolume.size }}'
        {{- if .Values.cluster.pods.persistentVolume.storageClass }}
        {{- if eq "-" .Values.cluster.pods.persistentVolume.storageClass }}
        storageClass: ""
        {{- else }}
        storageClass: {{ .Values.cluster.pods.persistentVolume.storageClass }}
        {{- end }}
        {{- end }}
  prometheusAutobind: {{ .Values.cluster.prometheusAutobind }}
  {{- if .Values.nonProductionOptions }}
  nonProductionOptions:
  {{- if not .Values.nonProductionOptions.disableClusterPodAntiAffinity }}
    disableClusterPodAntiAffinity: false
  {{- else }}
    disableClusterPodAntiAffinity: {{ .Values.nonProductionOptions.disableClusterPodAntiAffinity }}
  {{- end }}
  {{- if not .Values.nonProductionOptions.disablePatroniResourceRequirements }}
    disablePatroniResourceRequirements: false
  {{- else }}
    disablePatroniResourceRequirements: {{ .Values.nonProductionOptions.disablePatroniResourceRequirements }}
  {{- end }}
  {{- if not .Values.nonProductionOptions.disableClusterResourceRequirements }}
    disableClusterResourceRequirements: false
  {{- else }}
    disableClusterResourceRequirements: {{ .Values.nonProductionOptions.disableClusterResourceRequirements }}
  {{- end }}
  {{- if .Values.nonProductionOptions.enabledFeatureGates }}
    enabledFeatureGates:
  {{- range .Values.nonProductionOptions.enabledFeatureGates }}
    - '{{ . }}'
  {{- end }}
  {{- end }}
  {{- end }}
{{- end }}
