build:
  image: docker.io/ongres/ubi-graalvm-maven:20.1.0-java11
  stage: build
  tags:
    - stackgres-runner
  script:
    - 'mvn $MAVEN_CLI_OPTS clean verify -P safer'
  cache:
    paths:  
      - $CI_PROJECT_DIR/.m2/repository
  artifacts:
    expire_in: 1 week
    when: always
    paths:
      - stackgres-k8s/src/target
      - stackgres-k8s/src/*/target
    reports:
      junit:
        - stackgres-k8s/src/*/target/surefire-reports/TEST-*.xml

build ui:
  image: alpine:3.12
  stage: build
  script:
  - apk add py3-pip jq
  - pip install yamllint yq
  - sh -x stackgres-k8s/src/admin-ui/build.sh
  artifacts:
    expire_in: 1 week
    when: always
    paths:
    - stackgres-k8s/src/admin-ui/target

build documentation:
  image: monachus/hugo
  stage: build
  script:
  - |
    if [[ ! -z "$CI_COMMIT_TAG" && ! "$CI_COMMIT_TAG" =~ ^latest-.*$ ]]
    then
      DOCUMENTATION_BASE_URL="$PRODUCTION_DOCUMENTATION_BASE_URL"
    fi
  - sh -x doc/build.sh
  - STACKGRES_VERSION="$(echo 'import xml.etree.ElementTree as ET; print ET.parse("stackgres-k8s/src/pom.xml").getroot().find("{%s}version" % "http://maven.apache.org/POM/4.0.0").text' | python)"
  - mkdir -p "doc/public/$STACKGRES_VERSION"
  - hugo -v --source doc --destination "$(pwd)/doc/public/$STACKGRES_VERSION" --baseURL="$DOCUMENTATION_BASE_URL"
  - cp -a "doc/public/$STACKGRES_VERSION" doc/public/latest
  artifacts:
    expire_in: 1 week
    when: always
    paths:
    - doc/public

build helm packages:
  image: dtzar/helm-kubectl:3.1.1
  stage: build
  script:
  - sh -x stackgres-k8s/install/helm/build-helm-packages.sh
  - |
    if [[ ! -z "$CI_COMMIT_TAG" && ! "$CI_COMMIT_TAG" =~ ^latest-.*$ ]]
    then
      cp -a "stackgres-k8s/install/helm/target/public/downloads/stackgres-k8s/stackgres"/* stackgres-k8s/install/helm/target/public/downloads/stackgres-k8s/stackgres/latest
    fi
  - find stackgres-k8s/install/helm/target/public | sed -e "s/[^-][^\/]*\// |/g" -e "s/|\([^ ]\)/|-\1/"
  artifacts:
    expire_in: 1 week
    when: always
    paths:
    - stackgres-k8s/install/helm/target

build helm templates:
  image: dtzar/helm-kubectl:3.1.1
  stage: build
  script:
  - sh -x stackgres-k8s/install/helm/build-helm-templates.sh
  - |
    if [[ ! -z "$CI_COMMIT_TAG" && ! "$CI_COMMIT_TAG" =~ ^latest-.*$ ]]
    then
      cp -a "stackgres-k8s/install/helm/target/public/downloads/stackgres-k8s/stackgres"/* stackgres-k8s/install/helm/target/public/downloads/stackgres-k8s/stackgres/latest
    fi
  - find stackgres-k8s/install/helm/target/public | sed -e "s/[^-][^\/]*\// |/g" -e "s/|\([^ ]\)/|-\1/"
  artifacts:
    expire_in: 1 week
    when: always
    paths:
    - stackgres-k8s/install/helm/target
