build:
  image: docker.io/ongres/ubi-graalvm-maven:21.0.0.2-java11
  stage: build
  tags:
    - stackgres-runner-v2
    - stackgres-maven-runner
    - stackgres-quarkus-test-runner
  variables:
    KUBERNETES_MEMORY_REQUEST: 512Gi
    KUBERNETES_MEMORY_LIMIT: 512Gi
    KUBERNETES_CPU_REQUEST: 1
    KUBERNETES_CPU_LIMIT: 1
  script:
    - 'microdnf install python3-pip jq'
    - 'pip3 install yamllint yq'
    - 'mvn $MAVEN_CLI_OPTS clean verify -P safer'
    - 'sh -x stackgres-k8s/src/api-web/src/main/swagger/build.sh'
  cache:
    paths:
      - $CI_PROJECT_DIR/.m2/repository
  artifacts:
    expire_in: 1 week
    when: always
    paths:
      - stackgres-k8s/src/target
      - stackgres-k8s/src/*/target
    reports:
      junit:
        - stackgres-k8s/src/*/target/surefire-reports/TEST-*.xml
