build:
  image: registry.gitlab.com/$CI_PROJECT_PATH/$CI_IMAGE_NAME
  stage: build
  tags:
    - stackgres-runner
    - stackgres-maven-runner
  script:
    - |
      sh stackgres-k8s/ci/build/build-gitlab.sh \
        stackgres-parent \
        operator-framework \
        test-util \
        common \
        operator \
        restapi \
        jobs \
        cluster-controller \
        distributedlogs-controller
  retry:
    max: 2
    when: [ unknown_failure, api_failure, stuck_or_timeout_failure, runner_system_failure, runner_unsupported,
     stale_schedule, job_execution_timeout, archived_failure, unmet_prerequisites, scheduler_failure, data_integrity_failure ] 
  cache:
    paths:
      - stackgres-k8s/src/.m2/repository
      - stackgres-k8s/src/.mvn
  artifacts:
    expire_in: 1 week
    when: always
    paths:
      - stackgres-k8s/src/api-web/target/swagger*
      - stackgres-k8s/ci/build/target
    reports:
      junit:
        - stackgres-k8s/ci/build/target/junit-build.hashes.xml
        - stackgres-k8s/src/*/target/surefire-reports/TEST-*.xml

