build:
  image: registry.gitlab.com/$CI_PROJECT_PATH/$BUILD_IMAGE_NAME
  stage: build
  tags:
    - stackgres-runner-v2
    - stackgres-maven-runner
  script:
    - |
      cd stackgres-k8s/src
      ./mvnw $MAVEN_CLI_OPTS clean verify -P safer
      sh -x api-web/src/main/swagger/build.sh
  retry:
    max: 2
    when: [ unknown_failure, api_failure, stuck_or_timeout_failure, runner_system_failure, runner_unsupported,
     stale_schedule, job_execution_timeout, archived_failure, unmet_prerequisites, scheduler_failure, data_integrity_failure ] 
  cache:
    paths:
      - stackgres-k8s/src/.mvn/wrapper/maven-wrapper.jar
      - .m2/repository
  artifacts:
    expire_in: 1 week
    when: always
    paths:
      - stackgres-k8s/src/target
      - stackgres-k8s/src/*/target
    reports:
      junit:
        - stackgres-k8s/src/*/target/surefire-reports/TEST-*.xml

