
# Fail early if a tag is pushed but the project is still SNAPSHOT.
enforce release:
  image: $GRAALVM_IMAGE
  stage: .pre
  tags:
    - stackgres-runner
  script:
    - 'mvn $MAVEN_CLI_OPTS -q enforcer:enforce -Drules=requireReleaseVersion -Denforcer.failFast=true'
  rules:
    - if: '$CI_COMMIT_TAG && $CI_COMMIT_TAG !~ /^latest-.*$/'
