
.deploy image:
  image: quay.io/buildah/stable:v1.20.1
  stage: deploy
  tags:
    - stackgres-runner
  variables:
    IMAGE_TAG_SUFFIX: ""
  script:
    - set -e
    - buildah login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
    - set -x
    - export IMAGE_TAG="${CI_COMMIT_TAG:-"$CI_COMMIT_SHORT_SHA"}$IMAGE_TAG_SUFFIX"
    - export IMAGE_PUSH_TAG="${CI_COMMIT_TAG:-"$CI_COMMIT_REF_NAME"}$IMAGE_TAG_SUFFIX"
    - '[ -n "$IMAGE_NAME" ]'
    - export IMAGE_PULL_NAME="$CI_REGISTRY/$CI_PROJECT_PATH/$IMAGE_NAME:$IMAGE_TAG"
    - export IMAGE_PUSH_NAME="docker.io/$IMAGE_NAME:$IMAGE_PUSH_TAG"
    - buildah pull "$IMAGE_PULL_NAME"
    - buildah push --format=docker --authfile "$REGISTRY_AUTH_FILE" "$IMAGE_PULL_NAME" "docker://$IMAGE_PUSH_NAME"
  rules:
    - if: '$SKIP_DEPLOY != "true" && $CI_COMMIT_REF_NAME =~ /^development.*$/'
    - if: '$SKIP_DEPLOY != "true" && $CI_COMMIT_TAG && $CI_COMMIT_TAG !~ /^latest-.*$/'
    - if: '$DO_DEPLOY'
    - if: '$DOCS_ONLY'
      when: never

deploy operator jvm image:
  extends: .deploy image
  variables:
    IMAGE_TAG_SUFFIX: "-jvm"
    IMAGE_NAME: "stackgres/operator"


deploy restapi jvm image:
  extends: .deploy image
  variables:
    IMAGE_TAG_SUFFIX: "-jvm"
    IMAGE_NAME: "stackgres/restapi"

deploy jobs jvm image:
  extends: .deploy image
  variables:
    IMAGE_TAG_SUFFIX: "-jvm"
    IMAGE_NAME: "stackgres/jobs"

deploy cluster-controller jvm image:
  extends: .deploy image
  variables:
    IMAGE_TAG_SUFFIX: "-jvm"
    IMAGE_NAME: "stackgres/cluster-controller"

deploy distributedlogs-controller jvm image:
  extends: .deploy image
  variables:
    IMAGE_TAG_SUFFIX: "-jvm"
    IMAGE_NAME: "stackgres/distributedlogs-controller"

deploy operator native image:
  extends: .deploy image
  variables:
    IMAGE_TAG_SUFFIX: ""
    IMAGE_NAME: "stackgres/operator"
  rules:
    - if: '$SKIP_DEPLOY != "true" && $SKIP_NATIVE != "true" && $CI_COMMIT_REF_NAME =~ /^development.*$/'
    - if: '$SKIP_DEPLOY != "true" && $SKIP_NATIVE != "true" && $CI_COMMIT_TAG && $CI_COMMIT_TAG !~ /^latest-.*$/'
    - if: '$DO_DEPLOY'
    - if: '$DOCS_ONLY'
      when: never

deploy restapi native image:
  extends: .deploy image
  variables:
    IMAGE_TAG_SUFFIX: ""
    IMAGE_NAME: "stackgres/restapi"
  rules:
    - if: '$SKIP_DEPLOY != "true" && $SKIP_NATIVE != "true" && $CI_COMMIT_REF_NAME =~ /^development.*$/'
    - if: '$SKIP_DEPLOY != "true" && $SKIP_NATIVE != "true" && $CI_COMMIT_TAG && $CI_COMMIT_TAG !~ /^latest-.*$/'
    - if: '$DO_DEPLOY'
    - if: '$DOCS_ONLY'
      when: never

deploy job native image:
  extends: .deploy image
  variables:
    IMAGE_TAG_SUFFIX: ""
    IMAGE_NAME: "stackgres/jobs"
  rules:
    - if: '$SKIP_DEPLOY != "true" && $SKIP_NATIVE != "true" && $CI_COMMIT_REF_NAME =~ /^development.*$/'
    - if: '$SKIP_DEPLOY != "true" && $SKIP_NATIVE != "true" && $CI_COMMIT_TAG && $CI_COMMIT_TAG !~ /^latest-.*$/'
    - if: '$DO_DEPLOY'
    - if: '$DOCS_ONLY'
      when: never

deploy adminui image:
  extends: .deploy image
  variables:
    IMAGE_TAG_SUFFIX: ""
    IMAGE_NAME: "stackgres/admin-ui"

deploy cluster-controller native image:
  extends: .deploy image
  variables:
    IMAGE_TAG_SUFFIX: ""
    IMAGE_NAME: "stackgres/cluster-controller"
  rules:
    - if: '$SKIP_DEPLOY != "true" && $SKIP_NATIVE != "true" && $CI_COMMIT_REF_NAME =~ /^development.*$/'
    - if: '$SKIP_DEPLOY != "true" && $SKIP_NATIVE != "true" && $CI_COMMIT_TAG && $CI_COMMIT_TAG !~ /^latest-.*$/'
    - if: '$DO_DEPLOY'
    - if: '$DOCS_ONLY'
      when: never

deploy distributedlogs-controller native image:
  extends: .deploy image
  variables:
    IMAGE_TAG_SUFFIX: ""
    IMAGE_NAME: "stackgres/distributedlogs-controller"
  rules:
    - if: '$SKIP_DEPLOY != "true" && $SKIP_NATIVE != "true" && $CI_COMMIT_REF_NAME =~ /^development.*$/'
    - if: '$SKIP_DEPLOY != "true" && $SKIP_NATIVE != "true" && $CI_COMMIT_TAG && $CI_COMMIT_TAG !~ /^latest-.*$/'
    - if: '$DO_DEPLOY'
    - if: '$DOCS_ONLY'
      when: never

deploy helm packages and templates:
  image: mikesir87/aws-cli:latest
  stage: deploy
  dependencies:
    - build helm packages
    - build helm templates
  script:
    - set -e
    - aws s3 sync ./stackgres-k8s/install/helm/target/public/ s3://$S3_BUCKET_NAME/ --exclude "*" --include "downloads/*"
    - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths '/*'
  rules:
    - if: '$SKIP_DEPLOY != "true" && $CI_COMMIT_REF_NAME =~ /^development.*$/'
    - if: '$SKIP_DEPLOY != "true" && $CI_COMMIT_TAG && $CI_COMMIT_TAG !~ /^latest-.*$/'
    - if: '$DO_DEPLOY'
    - if: '$DOCS_ONLY'
      when: never
