
build operator jvm image:
  image: quay.io/buildah/stable:v1.15.0
  stage: image build
  tags:
    - stackgres-runner
  dependencies:
    - build
  timeout: 1 hour
  script:
    - 'export IMAGE_TAG="${CI_COMMIT_TAG:-"$CI_COMMIT_SHORT_SHA"}-jvm"'
    - 'export OPERATOR_IMAGE_NAME="stackgres/operator:$IMAGE_TAG"'
    - 'export TARGET_OPERATOR_IMAGE_NAME="$CI_REGISTRY/$CI_PROJECT_PATH/$OPERATOR_IMAGE_NAME"'
    - buildah login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
    - cd stackgres-k8s/src
    - |
      flock /tmp/stackgres-operator-build-jvm-image \
        sh -xe operator/src/main/buildah/build-image-jvm.sh

build restapi jvm image:
  image: quay.io/buildah/stable:v1.15.0
  stage: image build
  tags:
    - stackgres-runner
  dependencies:
    - build
  timeout: 1 hour
  script:
    - 'export IMAGE_TAG="${CI_COMMIT_TAG:-"$CI_COMMIT_SHORT_SHA"}-jvm"'
    - 'export RESTAPI_IMAGE_NAME="stackgres/restapi:$IMAGE_TAG"'
    - 'export TARGET_RESTAPI_IMAGE_NAME="$CI_REGISTRY/$CI_PROJECT_PATH/$RESTAPI_IMAGE_NAME"'
    - buildah login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
    - cd stackgres-k8s/src
    - |
      flock /tmp/stackgres-restapi-build-jvm-image \
        sh -xe api-web/src/main/buildah/build-image-jvm.sh

build operator native image:
  image: quay.io/buildah/stable:v1.15.0
  stage: image build
  tags:
    - stackgres-runner
  dependencies:
    - build operator native executable
  timeout: 1 hour
  script:
    - 'export IMAGE_TAG="${CI_COMMIT_TAG:-"$CI_COMMIT_SHORT_SHA"}"'
    - 'export OPERATOR_IMAGE_NAME="stackgres/operator:$IMAGE_TAG"'
    - 'export TARGET_OPERATOR_IMAGE_NAME="$CI_REGISTRY/$CI_PROJECT_PATH/$OPERATOR_IMAGE_NAME"'
    - buildah login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
    - cd stackgres-k8s/src
    - |
      flock /tmp/stackgres-operator-build-native-image \
        sh -xe operator/src/main/buildah/build-image-native.sh
  only:
    variables:
      - $SKIP_NATIVE != "true" && $CI_COMMIT_REF_NAME == "development"
      - $SKIP_NATIVE != "true" && $CI_COMMIT_REF_NAME == "master"
      - $SKIP_NATIVE != "true" && $CI_COMMIT_TAG && $CI_COMMIT_TAG !~ /^latest-.*$/
      - $DO_DEPLOY
      - $DO_NATIVE

build restapi native image:
  image: quay.io/buildah/stable:v1.15.0
  stage: image build
  tags:
    - stackgres-runner
  dependencies:
    - build restapi native executable
  timeout: 1 hour
  script:
    - 'export IMAGE_TAG="${CI_COMMIT_TAG:-"$CI_COMMIT_SHORT_SHA"}"'
    - 'export RESTAPI_IMAGE_NAME="stackgres/restapi:$IMAGE_TAG"'
    - 'export TARGET_RESTAPI_IMAGE_NAME="$CI_REGISTRY/$CI_PROJECT_PATH/$RESTAPI_IMAGE_NAME"'
    - buildah login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
    - cd stackgres-k8s/src
    - |
      flock /tmp/stackgres-restapi-build-native-image \
        sh -xe api-web/src/main/buildah/build-image-native.sh
  only:
    variables:
      - $SKIP_NATIVE != "true" && $CI_COMMIT_REF_NAME == "development"
      - $SKIP_NATIVE != "true" && $CI_COMMIT_REF_NAME == "master"
      - $SKIP_NATIVE != "true" && $CI_COMMIT_TAG && $CI_COMMIT_TAG !~ /^latest-.*$/
      - $DO_DEPLOY
      - $DO_NATIVE

build admin-ui image:
  image: quay.io/buildah/stable:v1.15.0
  stage: image build
  tags:
    - stackgres-runner
  dependencies:
    - build ui
  timeout: 1 hour
  script:
    - 'export IMAGE_TAG="${CI_COMMIT_TAG:-"$CI_COMMIT_SHORT_SHA"}"'
    - 'export ADMINUI_IMAGE_NAME="stackgres/admin-ui:$IMAGE_TAG"'
    - 'export TARGET_ADMINUI_IMAGE_NAME="$CI_REGISTRY/$CI_PROJECT_PATH/$ADMINUI_IMAGE_NAME"'
    - buildah login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
    - cd stackgres-k8s/src
    - |
      flock /tmp/stackgres-adminui-build-image \
        sh -xe admin-ui/buildah/build.sh

build test images:
  image: quay.io/buildah/stable:v1.15.0
  stage: image build
  tags:
    - stackgres-runner
  timeout: 1 hour
  script:
    - |
      IT_IMAGE_NAME="$(grep -o '<it\.image>\([^<]\+\)</it\.image>' stackgres-k8s/src/pom.xml \
        | tr '<>' '  ' | cut -d ' ' -f 3)"
    - TARGET_IT_IMAGE_NAME="$CI_REGISTRY/$CI_PROJECT_PATH/$IT_IMAGE_NAME"
    - buildah login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
    - |
      cat << EOF | flock /tmp/stackgres-build-it-image sh -xe
      buildah bud -f stackgres-k8s/src/operator/src/test/docker/Dockerfile.it -t "$IT_IMAGE_NAME" .
      buildah push -f "docker" "$IT_IMAGE_NAME" "$TARGET_IT_IMAGE_NAME"
      EOF
  only:
    variables:
      - $SKIP_E2E != "true"
