
.build native executable:
  image: docker.io/ongres/ubi-graalvm-maven:19.3.1-java8
  stage: native build
  tags:
    - stackgres-runner
    - stackgres-native-build-runner
  dependencies:
    - build
  variables:
    NATIVE_IMAGE_EXTRA_PREFIX: ""
    MAVEN_EXTRA_ARGS: ""
  timeout: 12 hour
  script:
    - MAVEN_CLI_OPTS="$MAVEN_CLI_OPTS -DskipTests"
    - |
      flock "/tmp/stackgres-build$NATIVE_IMAGE_EXTRA_PREFIX-native-executable" \
        timeout -s KILL 3600 \
        mvn $MAVEN_CLI_OPTS package -P native $MAVEN_EXTRA_ARGS
    - 'cp $GRAALVM_HOME/jre/lib/amd64/libsunec.so stackgres-k8s/src/operator/target/'
    - 'cp $GRAALVM_HOME/jre/lib/security/cacerts stackgres-k8s/src/operator/target/'
    - 'cp $GRAALVM_HOME/jre/lib/amd64/libsunec.so stackgres-k8s/src/api-web/target/'
    - 'cp $GRAALVM_HOME/jre/lib/security/cacerts stackgres-k8s/src/api-web/target/'
  artifacts:
    expire_in: 1 week
    when: always
    paths:
      - stackgres-k8s/src/*/target/libsunec.so
      - stackgres-k8s/src/*/target/cacerts
      - stackgres-k8s/src/*/target/stackgres-*-runner
      - stackgres-k8s/src/*/target/lib/
      - stackgres-k8s/src/*/target/stackgres-*-runner.jar
  only:
    variables:
      - $SKIP_E2E != "true" && $SKIP_NATIVE != "true" && $CI_COMMIT_REF_NAME =~ /^main.*$/
      - $SKIP_E2E != "true" && $SKIP_NATIVE != "true" && $CI_COMMIT_REF_NAME == "current"
      - $SKIP_E2E != "true" && $SKIP_NATIVE != "true" && $CI_COMMIT_TAG && $CI_COMMIT_TAG !~ /^latest-.*$/
      - $DO_DEPLOY
      - $DO_NATIVE

build operator native executable:
  extends: .build native executable
  variables:
    NATIVE_IMAGE_EXTRA_PREFIX: "-operator"
    MAVEN_EXTRA_ARGS: "-pl .,common,operator-framework,test-util,operator"

build restapi native executable:
  extends: .build native executable
  variables:
    NATIVE_IMAGE_EXTRA_PREFIX: "-restapi"
    MAVEN_EXTRA_ARGS: "-pl .,common,operator-framework,test-util,api-web"
