
.build native executable:
  image: $GRAALVM_IMAGE
  stage: native build
  tags:
    - stackgres-runner
    - stackgres-native-build-runner
  dependencies:
    - build
  variables:
    NATIVE_IMAGE_EXTRA_PREFIX: ""
    MAVEN_EXTRA_ARGS: ""
    QUARKUS_NATIVE_NATIVE_IMAGE_XMX: 18g
  timeout: 3 hour
  script:
    - MAVEN_CLI_OPTS="$MAVEN_CLI_OPTS -DskipTests"
    - |
      flock "/tmp/stackgres-build$NATIVE_IMAGE_EXTRA_PREFIX-native-executable" \
        timeout -s KILL 3600 \
        mvn $MAVEN_CLI_OPTS package -P native $MAVEN_EXTRA_ARGS
  artifacts:
    expire_in: 1 week
    when: always
    paths:
      - stackgres-k8s/src/*/target/stackgres-*-runner
      - stackgres-k8s/src/*/target/lib/
      - stackgres-k8s/src/*/target/stackgres-*-runner.jar
  rules:
    - if: '$SKIP_E2E != "true" && $SKIP_NATIVE != "true" && $CI_COMMIT_REF_NAME =~ /^development.*$/'
    - if: '$SKIP_E2E != "true" && $SKIP_NATIVE != "true" && $CI_COMMIT_REF_NAME == "master"'
    - if: '$SKIP_E2E != "true" && $SKIP_NATIVE != "true" && $CI_COMMIT_TAG && $CI_COMMIT_TAG !~ /^latest-.*$/'
    - if: '$DO_DEPLOY'
    - if: '$DO_NATIVE'
    - if: '$DOCS_ONLY'
      when: never
    - when: on_success

build operator native executable:
  extends: .build native executable
  variables:
    NATIVE_IMAGE_EXTRA_PREFIX: "-operator"
    MAVEN_EXTRA_ARGS: "-pl .,common,operator-framework,test-util,operator"

build restapi native executable:
  extends: .build native executable
  variables:
    NATIVE_IMAGE_EXTRA_PREFIX: "-restapi"
    MAVEN_EXTRA_ARGS: "-pl .,common,operator-framework,test-util,api-web"

build jobs native executable:
  extends: .build native executable
  variables:
    NATIVE_IMAGE_EXTRA_PREFIX: "-jobs"
    MAVEN_EXTRA_ARGS: "-pl .,common,operator-framework,test-util,jobs"

build cluster-controller native executable:
  extends: .build native executable
  variables:
    NATIVE_IMAGE_EXTRA_PREFIX: "-cluster-controller"
    MAVEN_EXTRA_ARGS: "-pl .,common,operator-framework,test-util,cluster-controller"

build distributedlogs-controller native executable:
  extends: .build native executable
  variables:
    NATIVE_IMAGE_EXTRA_PREFIX: "-distributedlogs-controller"
    MAVEN_EXTRA_ARGS: "-pl .,common,operator-framework,test-util,distributedlogs-controller"
