
.build native executable:
  image: registry.gitlab.com/$CI_PROJECT_PATH/$BUILD_IMAGE_NAME
  stage: native build
  dependencies:
    - build
  variables:
    NATIVE_IMAGE_EXTRA_PREFIX: ""
    MAVEN_EXTRA_ARGS: ""
    QUARKUS_NATIVE_NATIVE_IMAGE_XMX: 18g
  timeout: 12 hour
  script:
    - MAVEN_CLI_OPTS="$MAVEN_CLI_OPTS -DskipTests"
    - |
      cd stackgres-k8s/src
      flock "/tmp/stackgres-build$NATIVE_IMAGE_EXTRA_PREFIX-native-executable" \
        timeout -s KILL 3600 \
        ./mvnw $MAVEN_CLI_OPTS package -P native $MAVEN_EXTRA_ARGS
  retry:
    max: 2
    when: [ unknown_failure, api_failure, stuck_or_timeout_failure, runner_system_failure, runner_unsupported,
     stale_schedule, job_execution_timeout, archived_failure, unmet_prerequisites, scheduler_failure, data_integrity_failure ] 
  artifacts:
    expire_in: 1 week
    when: always
    paths:
      - stackgres-k8s/src/*/target/stackgres-*-runner
      - stackgres-k8s/src/*/target/lib/
      - stackgres-k8s/src/*/target/stackgres-*-runner.jar

.build native executable amd64:
  extends: .build native executable
  tags:
    - stackgres-runner-v2
    - stackgres-native-build-runner
    - linux-amd64
  only:
    variables:
      - $SKIP_NATIVE != "true" && $CI_COMMIT_REF_NAME =~ /^main.*$/
      - $SKIP_NATIVE != "true" && $CI_COMMIT_REF_NAME == "current"
      - $SKIP_NATIVE != "true" && $CI_COMMIT_TAG && $CI_COMMIT_TAG !~ /^latest-.*$/
      - $DO_DEPLOY
      - $DO_NATIVE

build operator native executable amd64:
  extends: .build native executable amd64
  variables:
    NATIVE_IMAGE_EXTRA_PREFIX: "-operator"
    MAVEN_EXTRA_ARGS: "-pl .,common,operator-framework,test-util,operator"

build restapi native executable amd64:
  extends: .build native executable amd64
  variables:
    NATIVE_IMAGE_EXTRA_PREFIX: "-restapi"
    MAVEN_EXTRA_ARGS: "-pl .,common,operator-framework,test-util,api-web"

build jobs native executable amd64:
  extends: .build native executable amd64
  variables:
    NATIVE_IMAGE_EXTRA_PREFIX: "-jobs"
    MAVEN_EXTRA_ARGS: "-pl .,common,operator-framework,test-util,jobs"

build cluster-controller native executable amd64:
  extends: .build native executable amd64
  variables:
    NATIVE_IMAGE_EXTRA_PREFIX: "-cluster-controller"
    MAVEN_EXTRA_ARGS: "-pl .,common,operator-framework,test-util,cluster-controller"

build distributedlogs-controller native executable amd64:
  extends: .build native executable amd64
  variables:
    NATIVE_IMAGE_EXTRA_PREFIX: "-distributedlogs-controller"
    MAVEN_EXTRA_ARGS: "-pl .,common,operator-framework,test-util,distributedlogs-controller"

.build native executable arm64:
  extends: .build native executable
  tags:
    - stackgres-runner-v2
    - stackgres-native-build-runner
    - linux-arm64
  only:
    variables:
      - $SKIP_NATIVE != "true" && $SKIP_ARM != "true" && $CI_COMMIT_REF_NAME =~ /^main.*$/
      - $SKIP_NATIVE != "true" && $SKIP_ARM != "true" && $CI_COMMIT_REF_NAME == "current"
      - $SKIP_NATIVE != "true" && $SKIP_ARM != "true" && $CI_COMMIT_TAG && $CI_COMMIT_TAG !~ /^latest-.*$/
      - $DO_DEPLOY
      - $DO_NATIVE && $DO_ARM

build operator native executable arm64:
  extends: .build native executable arm64
  variables:
    NATIVE_IMAGE_EXTRA_PREFIX: "-operator"
    MAVEN_EXTRA_ARGS: "-pl .,common,operator-framework,test-util,operator"

build restapi native executable arm64:
  extends: .build native executable arm64
  variables:
    NATIVE_IMAGE_EXTRA_PREFIX: "-restapi"
    MAVEN_EXTRA_ARGS: "-pl .,common,operator-framework,test-util,api-web"

build jobs native executable arm64:
  extends: .build native executable arm64
  variables:
    NATIVE_IMAGE_EXTRA_PREFIX: "-jobs"
    MAVEN_EXTRA_ARGS: "-pl .,common,operator-framework,test-util,jobs"

build cluster-controller native executable arm64:
  extends: .build native executable arm64
  variables:
    NATIVE_IMAGE_EXTRA_PREFIX: "-cluster-controller"
    MAVEN_EXTRA_ARGS: "-pl .,common,operator-framework,test-util,cluster-controller"

build distributedlogs-controller native executable arm64:
  extends: .build native executable arm64
  variables:
    NATIVE_IMAGE_EXTRA_PREFIX: "-distributedlogs-controller"
    MAVEN_EXTRA_ARGS: "-pl .,common,operator-framework,test-util,distributedlogs-controller"
