build ui:
  image: alpine:3.12
  stage: post-build
  script:
  - sh -x stackgres-k8s/src/admin-ui/build.sh
  artifacts:
    expire_in: 1 week
    when: always
    paths:
    - stackgres-k8s/src/admin-ui/target

build documentation:
  image: monachus/hugo
  stage: post-build
  dependencies:
    - build
  script:
  - sh -x doc/build.sh
  - |
    STACKGRES_VERSION="$(
      grep '<artifactId>stackgres-parent</artifactId>' "stackgres-k8s/src/pom.xml" -A 2 -B 2 \
      | grep -oP '(?<=<version>).*?(?=</version>)')"
    STACKGRES_DOC_VERSION="$(printf "%s" "$STACKGRES_VERSION" | cut -d . -f 1-2)$(printf "%s" "$STACKGRES_VERSION" \
      | grep -q ".-SNAPSHOT$" && printf "%s" "-dev" || true)"
  - |
    if [[ ! -z "$CI_COMMIT_TAG" && ! "$CI_COMMIT_TAG" =~ ^latest-.*$ ]]
    then
      DOCUMENTATION_BASE_URL="https://stackgres.io/doc"
    else
      DOCUMENTATION_BASE_URL="https://ongresinc.gitlab.io/stackgres"
    fi
  - mkdir -p "doc/public/$STACKGRES_VERSION"
  - hugo -v --source doc --destination "$(pwd)/doc/public/$STACKGRES_DOC_VERSION" --baseURL="$DOCUMENTATION_BASE_URL/$STACKGRES_DOC_VERSION"
  - |
    if [ "$LATEST" = true ]
    then
      hugo -v --source doc --destination "$(pwd)/doc/public/latest" --baseURL="$DOCUMENTATION_BASE_URL/latest"
    fi
  artifacts:
    expire_in: 1 week
    when: always
    paths:
    - doc/public

build helm packages:
  image: dtzar/helm-kubectl:3.3.1
  stage: post-build
  script:
  - sh -x stackgres-k8s/install/helm/build-helm-packages.sh
  - |
    if [[ ! -z "$CI_COMMIT_TAG" && ! "$CI_COMMIT_TAG" =~ ^latest-.*$ ]]
    then
      cp -a "stackgres-k8s/install/helm/target/public/downloads/stackgres-k8s/stackgres"/* stackgres-k8s/install/helm/target/public/downloads/stackgres-k8s/stackgres/latest
    fi
  - find stackgres-k8s/install/helm/target/public | sed -e "s/[^-][^\/]*\// |/g" -e "s/|\([^ ]\)/|-\1/"
  artifacts:
    expire_in: 1 week
    when: always
    paths:
    - stackgres-k8s/install/helm/target

build helm templates:
  image: dtzar/helm-kubectl:3.3.1
  stage: post-build
  script:
  - sh -x stackgres-k8s/install/helm/build-helm-templates.sh
  - |
    if [[ ! -z "$CI_COMMIT_TAG" && ! "$CI_COMMIT_TAG" =~ ^latest-.*$ ]]
    then
      cp -a "stackgres-k8s/install/helm/target/public/downloads/stackgres-k8s/stackgres"/* stackgres-k8s/install/helm/target/public/downloads/stackgres-k8s/stackgres/latest
    fi
  - find stackgres-k8s/install/helm/target/public | sed -e "s/[^-][^\/]*\// |/g" -e "s/|\([^ ]\)/|-\1/"
  artifacts:
    expire_in: 1 week
    when: always
    paths:
    - stackgres-k8s/install/helm/target
