instanceProfiles: false
configurations:
  postgresconfig:
    postgresql.conf:
      shared_buffers: '32MB'
  backupconfig:
    create: false
cluster:
  pods:
    persistentVolume:
      size: 128Mi
    managementPolicy: Parallel
  configurations:
    sgBackupConfig: null
  sgInstanceProfile: 'size-s'
  prometheusAutobind: false
nonProductionOptions:
  disableClusterPodAntiAffinity: true
