apiVersion: v1
kind: Namespace
metadata:
  labels:
    app: stackgres-helm-controller-manager
    app.kubernetes.io/name: namespace
    app.kubernetes.io/instance: system
    app.kubernetes.io/component: manager
    app.kubernetes.io/created-by: stackgres
    app.kubernetes.io/part-of: stackgres
    app.kubernetes.io/managed-by: kustomize
  name: system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helm-controller-manager
  namespace: system
  labels:
    app: stackgres-helm-controller-manager
    app.kubernetes.io/name: deployment
    app.kubernetes.io/instance: controller-manager
    app.kubernetes.io/component: manager
    app.kubernetes.io/created-by: stackgres
    app.kubernetes.io/part-of: stackgres
    app.kubernetes.io/managed-by: kustomize
spec:
  selector:
    matchLabels:
      app: stackgres-helm-controller-manager
  replicas: 1
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        app: stackgres-helm-controller-manager
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: kubernetes.io/arch
                  operator: In
                  values:
                    - amd64
                    - arm64
                - key: kubernetes.io/os
                  operator: In
                  values:
                    - linux
      securityContext:
        runAsNonRoot: true
        # TODO(user): For common cases that do not require escalating privileges
        # it is recommended to ensure that all your Pods/Containers are restrictive.
        # More info: https://kubernetes.io/docs/concepts/security/pod-security-standards/#restricted
        # Please uncomment the following code if your project does NOT have to work on old Kubernetes
        # versions < 1.19 or on vendors versions which do NOT support this field by default (i.e. Openshift < 4.11 ).
        # seccompProfile:
        #   type: RuntimeDefault
      containers:
      - args:
        - --leader-elect
        - --leader-election-id=stackgres
        image: controller:latest
        imagePullPolicy: IfNotPresent
        name: manager
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - "ALL"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        # TODO(user): Configure the resources accordingly based on the project requirements.
        # More info: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
        resources:
          limits:
            cpu: 1
            memory: 512Mi
          requests:
            cpu: 10m
            memory: 128Mi
      initContainers:
      - command:
        - sh
        - -exc
        - |
          # TODO: Remove this as soon as version 1.4 get out of support!
          PREVIOUS_SGCONFIG="$(kubectl get sgconfig stackgres -o yaml || true)"
          if [ "x" = "x$SGCONFIG" ] \
            && [ "x" != "x$PREVIOUS_SGCONFIG" ]
          then
            SGCONFIG="$PREVIOUS_SGCONFIG"
          fi

          SGCONFIG_SPEC=""
          if [ "x" != "x$SGCONFIG" ]
          then
            if ! SGCONFIG="$(printf %s "$SGCONFIG" | kubectl create -f - --dry-run=client -o yaml)"
            then
              printf "Please set a correct value for SGCONFIG env var in Subscription since the following is invalid:\n\n%s\n" "$SGCONFIG"
              exit 1
            fi
            if printf %s "$SGCONFIG" | grep -q '^spec:$'
            then
              echo "Found SGConfig spec"
              SGCONFIG_SPEC_LINE="\$(printf %s "\$SGCONFIG" \
                | grep -n '^spec:$' | cut -d : -f 1)"
              SGCONFIG_AFTER_SPEC_LINE="\$(printf %s "\$SGCONFIG" \
                | tail -n +"\$((SGCONFIG_SPEC_LINE + 1))" \
                | grep -n '^[^ #].*$' | cut -d : -f 1)"
              if [ x != "x$SGCONFIG_AFTER_SPEC_LINE" ]
              then
                SGCONFIG_SPEC="\$(printf %s "\$SGCONFIG" \
                  | head -n "\$((SGCONFIG_SPEC_LINE + SGCONFIG_AFTER_SPEC_LINE - 1))" \
                  | tail -n +"\$((SGCONFIG_AFTER_SPEC_LINE - 1))")"
              else
                SGCONFIG_SPEC="\$(printf %s "\$SGCONFIG" \
                  | tail -n +"\$((SGCONFIG_SPEC_LINE + 1))")"
              fi
            else
              echo "Found SGConfig without spec, ignoring!"
            fi
          fi

          OPERATOR_NAME="\$(kubectl get operators.operators.coreos.com -o name \
            | grep '^operator.operators.coreos.com/stackgres' \
            | head -n 1 | cut -d / -f 2)"
          test -n "\$OPERATOR_NAME"
          OPERATOR_UID="\$(kubectl get operators.operators.coreos.com "\$OPERATOR_NAME" --template '{{ .metadata.uid }}')"
          test -n "\$OPERATOR_UID"

          cat << EOF | kubectl apply -f -
          apiVersion: stackgres.io/v1
          kind: SGConfig
          metadata:
            name: stackgres-operator
          spec:
          \$SGCONFIG_SPEC
            clusterOwnerReferences:
            - apiVersion: operators.coreos.com/v1
              kind: Operator
              name: \$OPERATOR_NAME
              uid: \$OPERATOR_UID
          EOF

          # TODO: Remove this as soon as version 1.4 get out of support!
          kubectl delete --ignore-not-found sgconfig stackgres
          kubectl delete --ignore-not-found clusterrole stackgres
          kubectl delete --ignore-not-found clusterrole stackgres-restapi
          kubectl delete --ignore-not-found clusterrolebinding stackgres
          kubectl delete --ignore-not-found clusterrolebinding stackgres-restapi
          kubectl delete --ignore-not-found clusterrolebinding stackgres-restapi-admin
          kubectl delete --ignore-not-found validatingwebhookconfiguration stackgres
          kubectl delete --ignore-not-found mutatingwebhookconfiguration stackgres
          kubectl delete --ignore-not-found secret stackgres-certs
          kubectl delete --ignore-not-found secret stackgres-web-certs
          kubectl wait sgconfig stackgres-operator --for condition=Deployed
        image: ongres/kubectl:v1.25.5-build-6.19
        imagePullPolicy: IfNotPresent
        name: default
        securityContext:
          runAsNonRoot: true
$(
if [ "$OPENSHIFT_BUNDLE" != true ]
then
  cat << EOF
          runAsUser: 1000
          runAsGroup: 1000
EOF
fi
)
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - "ALL"
        # TODO(user): Configure the resources accordingly based on the project requirements.
        # More info: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
        resources:
          limits:
            cpu: 1
            memory: 512Mi
          requests:
            cpu: 10m
            memory: 128Mi
      serviceAccountName: helm-controller-manager
      terminationGracePeriodSeconds: 10
