apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: operator-role
rules:
##
## Base operator rules
##
- apiGroups:
    - ''
    - apps
    - extensions
    - rbac.authorization.k8s.io
    - batch
  resources:
    - pods
    - pods/exec
    - pods/log
    - services
    - endpoints
    - endpoints/restricted
    - persistentvolumeclaims
    - configmaps
    - secrets
    - statefulsets
    - serviceaccounts
    - namespaces
    - roles
    - rolebindings
    - events
    - cronjobs
    - persistentvolumeclaims
    - jobs
  verbs:
    - get
    - list
    - watch
    - update
    - create
    - delete
    - patch
- apiGroups:
    - storage.k8s.io
  resources:
    - storageclasses
  verbs:
    - get
    - list
- apiGroups:
    - apiextensions.k8s.io
  resources:
    - customresourcedefinitions
  verbs:
    - get
    - list
    - watch
- apiGroups:
    - stackgres.io
  resources:
    - sgclusters
    - sgpgconfigs
    - sginstanceprofiles
    - sgpoolconfigs
    - sgbackupconfigs
    - sgbackups
    - sgdistributedlogs
    - sgdbops
    - sgobjectstorages
    - sgscripts
    - sgshardedclusters
    - sgconfigs
    - sgconfigs/status
  verbs:
    - create
    - watch
    - list
    - get
    - update
    - patch
    - delete
- apiGroups:
    - stackgres.io
  resources:
    - sgclusters/status
    - sgdistributedlogs/status
  verbs:
    - update
- apiGroups:
    - monitoring.coreos.com
  resources:
    - servicemonitors
    - podmonitors
  verbs:
    - list
    - get
    - create
    - delete
    - update
    - patch
- apiGroups:
    - monitoring.coreos.com
  resources:
    - prometheus
    - prometheuses
    - podmonitors
  verbs:
    - list
    - get

- apiGroups:
  - operators.coreos.com
  resources:
  - operators
  verbs:
  - list
  - get

# TODO Remove when stackgres 1.5 get out of support
- apiGroups:
  - certificates.k8s.io
  resources:
  - certificatesigningrequests
  verbs:
  - delete
  resourceNames:
  - stackgres
  - stackgres-operator
- apiGroups:
  - "apps"
  resources:
  - "deployments"
  verbs:
  - list
  - delete
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - mutatingwebhookconfigurations
  - validatingwebhookconfigurations
  resourceNames:
  - stackgres
  - stackgres-operator
  verbs:
  - delete
- apiGroups:
  - "rbac.authorization.k8s.io"
  resources:
  - "clusterrolebindings"
  - "clusterroles"
  resourceNames:
  - stackgres
  - stackgres-operator
  - stackgres-restapi
  - stackgres-restapi-admin
  verbs:
  - delete
- apiGroups:
  - ""
  resources:
  - configmap
  - secret
  resourceNames:
  - stackgres
  - stackgres-certs
  - stackgres-web-certs
  - stackgres-service-certs
  - stackgres-restapi
  - stackgres-restapi-nginx
  - stackgres-grafana-dashboard
  - stackgres-operator
  - stackgres-operator-certs
  - stackgres-operator-web-certs
  - stackgres-operator-service-certs
  - stackgres-operator-grafana-dashboard
  verbs:
  - delete

#+kubebuilder:scaffold:rules
