# permissions for end users to view sgconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: sgconfig-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: stackgres-operator
    app.kubernetes.io/part-of: stackgres-operator
    app.kubernetes.io/managed-by: kustomize
  name: sgconfig-viewer-role
rules:
- apiGroups:
  - stackgres.io
  resources:
  - *
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - stackgres.io
  resources:
  - sgconfigs/status
  verbs:
  - get
