apiVersion: stackgres.io/v1
kind: SGPoolingConfig
metadata:
  name: poolconfig
  namespace: demo-db
spec:
  pgBouncer:
    pgbouncer.ini:
      pgbouncer:
        pool_mode: session
        max_client_conn: '2000'
        default_pool_size: '100'
      databases:
        demo:
          pool_size: 400
          dbname: 'demo'
          reserve_pool: 5
        postgres:
          pool_size: 10
          dbname: 'postgres'
          reserve_pool: 5
