apiVersion: v1
kind: Pod
metadata:
  name: pgbench
  namespace: test
spec:
  containers:
  - name: pgbench
    image: postgres
    args:
    - sleep
    - "1000000"
    env:
      - name: PGSERVICE
        value: pgbench
      - name: PGSERVICEFILE
        value: /root/.pg_service.conf
    volumeMounts:
    - name: workdir
      mountPath: /root/.pgpass
      subPath: .pgpass
    - name: creds
      mountPath: /root/.pg_service.conf
      subPath: .pg_service.conf
    resources:
      requests:
        memory: "128Mi"
        cpu: "250m"
      limits:
        memory: "256Mi"
        cpu: "500m"    
  initContainers:
  - name: install
    image: "ongres/kubectl:v1.23.3-build-6.10"
    command:
    - "/bin/bash"
    - "-ecx"
    - |
      cp /creds/.pgpass /work-dir/.pgpass
      chmod 600 /work-dir/.pgpass
    volumeMounts:
    - name: creds
      mountPath: "/creds/.pgpass"
      subPath: .pgpass
    - name: workdir
      mountPath: /work-dir
  volumes:
  - name: workdir
    emptyDir:   
  - name: creds
    secret:
      secretName: pgbench