configurations:
  postgresconfig:
    postgresql.conf:
      shared_buffers: '32MB'
  backupconfig:
    create: false
cluster:
  pods:
    persistentVolume:
      size: 128Mi
  configurations:
    sgBackupConfig: null
  prometheusAutobind: false
  initialData:
    scripts:
      - script: 'CREATE EXTENSION pg_repack'
  postgresExtensions:
    - name: pg_repack
nonProductionOptions:
  disableClusterPodAntiAffinity: true
