configurations:
  postgresconfig:
    postgresql.conf:
      shared_buffers: '32MB'
  objectstorage:
    create: true
cluster:
  configurations:
    backups:
      cronSchedule: '0 5 31 2 *'
  pods:
    persistentVolume:
      size: 128Mi
  prometheusAutobind: false
nonProductionOptions:
  disableClusterPodAntiAffinity: true
