apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "charts.stackgres.io/v1",
          "kind": "StackGresOperator",
          "metadata": {
            "name": "stackgres-operator"
          },
          "spec": {
            "adminui": {
              "image": {
                "name": "stackgres/admin-ui",
                "pullPolicy": "IfNotPresent",
                "tag": "1.4.1"
              },
              "name": "stackgres-adminui",
              "resources": {},
              "service": {
                "exposeHTTP": false,
                "type": "ClusterIP"
              }
            },
            "authentication": {
              "oidc": {},
              "resetPassword": false,
              "secretRef": {
                "name": ""
              },
              "type": "jwt",
              "user": "admin"
            },
            "cert": {
              "autoapprove": true,
              "certManager": {
                "autoConfigure": false,
                "duration": "2160h",
                "encoding": "PKCS1",
                "renewBefore": "360h",
                "size": 2048
              },
              "createForOperator": true,
              "createForWebApi": true,
              "crt": null,
              "jwtRsaKey": null,
              "jwtRsaPub": null,
              "key": null,
              "resetCerts": false,
              "webCrt": null,
              "webKey": null
            },
            "containerRegistry": "docker.io",
            "deploy": {
              "operator": true,
              "restapi": true
            },
            "developer": {},
            "extensions": {
              "cache": {
                "enabled": false,
                "persistentVolume": {
                  "size": "1Gi"
                },
                "preloadedExtensions": [
                  "x86_64/linux/timescaledb-1\\.7\\.4-pg12"
                ]
              },
              "repositoryUrls": [
                "https://extensions.stackgres.io/postgres/repository"
              ]
            },
            "grafana": {
              "autoEmbed": false,
              "datasourceName": "Prometheus",
              "password": "prom-operator",
              "schema": "http",
              "user": "admin"
            },
            "imagePullPolicy": "IfNotPresent",
            "initClusterRole": "cluster-admin",
            "jobs": {
              "affinity": {},
              "annotations": {},
              "image": {
                "name": "stackgres/jobs",
                "pullPolicy": "IfNotPresent",
                "tag": "1.4.1"
              },
              "name": "stackgres-jobs",
              "nodeSelector": {},
              "resources": {},
              "tolerations": []
            },
            "operator": {
              "affinity": {},
              "annotations": {},
              "image": {
                "name": "stackgres/operator",
                "pullPolicy": "IfNotPresent",
                "tag": "1.4.1"
              },
              "nodeSelector": {},
              "resources": {},
              "service": {
                "annotations": {}
              },
              "serviceAccount": {
                "annotations": {}
              },
              "tolerations": []
            },
            "prometheus": {
              "allowAutobind": true
            },
            "rbac": {
              "create": true
            },
            "restapi": {
              "affinity": {},
              "annotations": {},
              "image": {
                "name": "stackgres/restapi",
                "pullPolicy": "IfNotPresent",
                "tag": "1.4.1"
              },
              "name": "stackgres-restapi",
              "nodeSelector": {},
              "resources": {},
              "service": {
                "annotations": {}
              },
              "serviceAccount": {
                "annotations": {}
              },
              "tolerations": []
            },
            "serviceAccount": {
              "create": true
            }
          }
        }
      ]
    capabilities: Basic Install
    createdAt: "2023-01-13T13:47:02Z"
    operators.operatorframework.io/builder: operator-sdk-v1.26.0
    operators.operatorframework.io/project_layout: helm.sdk.operatorframework.io/v1
  name: stackgres-operator.v1.4.1
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - kind: StackGresOperator
      name: stackgresoperators.charts.stackgres.io
      version: v1
  description: StackGres Operator
  displayName: stackgres-operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - namespaces
          verbs:
          - get
          - create
        - apiGroups:
          - ""
          resources:
          - secrets
          verbs:
          - '*'
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
        - apiGroups:
          - charts.stackgres.io
          resources:
          - stackgresoperators
          - stackgresoperators/status
          - stackgresoperators/finalizers
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - rbac.authorization.k8s.io
          resources:
          - clusterrolebindings
          - clusterroles
          verbs:
          - '*'
        - apiGroups:
          - ""
          resources:
          - configmaps
          - secrets
          - serviceaccounts
          - services
          verbs:
          - '*'
        - apiGroups:
          - apps
          resources:
          - deployments
          verbs:
          - '*'
        - apiGroups:
          - batch
          resources:
          - jobs
          verbs:
          - '*'
        - apiGroups:
          - certificates.k8s.io
          resources:
          - certificatesigningrequests
          verbs:
          - list
        - apiGroups:
          - certificates.k8s.io
          resourceNames:
          - stackgres-operator
          resources:
          - certificatesigningrequests
          verbs:
          - create
          - get
          - list
          - watch
        - apiGroups:
          - certificates.k8s.io
          resources:
          - certificatesigningrequests/approval
          verbs:
          - update
        - apiGroups:
          - certificates.k8s.io
          resourceNames:
          - stackgres-operator.stackgres/*
          resources:
          - signers
          verbs:
          - approve
        - apiGroups:
          - admissionregistration.k8s.io
          resourceNames:
          - stackgres-operator
          resources:
          - mutatingwebhookconfigurations
          - validatingwebhookconfigurations
          verbs:
          - '*'
        - apiGroups:
          - apiextensions.k8s.io
          resources:
          - customresourcedefinitions
          verbs:
          - list
        - apiGroups:
          - apiextensions.k8s.io
          resourceNames:
          - sgbackupconfigs.stackgres.io
          - sgbackups.stackgres.io
          - sgclusters.stackgres.io
          - sgdbops.stackgres.io
          - sgdistributedlogs.stackgres.io
          - sginstanceprofiles.stackgres.io
          - sgobjectstorages.stackgres.io
          - sgpgconfigs.stackgres.io
          - sgpoolconfigs.stackgres.io
          - sgscripts.stackgres.io
          resources:
          - customresourcedefinitions
          verbs:
          - '*'
        - apiGroups:
          - stackgres.io
          resources:
          - sgbackupconfigs
          - sgbackups
          - sgclusters
          - sgdbops
          - sgdistributedlogs
          - sginstanceprofiles
          - sgobjectstorages
          - sgpgconfigs
          - sgpoolconfigs
          - sgscripts
          verbs:
          - '*'
        - apiGroups:
          - authentication.k8s.io
          resources:
          - tokenreviews
          verbs:
          - create
        - apiGroups:
          - authorization.k8s.io
          resources:
          - subjectaccessreviews
          verbs:
          - create
        serviceAccountName: stackgres-operator-controller-manager
      deployments:
      - label:
          app.kubernetes.io/component: manager
          app.kubernetes.io/created-by: stackgres-operator
          app.kubernetes.io/instance: controller-manager
          app.kubernetes.io/managed-by: kustomize
          app.kubernetes.io/name: deployment
          app.kubernetes.io/part-of: stackgres-operator
          control-plane: controller-manager
        name: stackgres-operator-controller-manager
        spec:
          replicas: 1
          selector:
            matchLabels:
              control-plane: controller-manager
          strategy: {}
          template:
            metadata:
              annotations:
                kubectl.kubernetes.io/default-container: manager
              labels:
                control-plane: controller-manager
            spec:
              affinity:
                nodeAffinity:
                  requiredDuringSchedulingIgnoredDuringExecution:
                    nodeSelectorTerms:
                    - matchExpressions:
                      - key: kubernetes.io/arch
                        operator: In
                        values:
                        - amd64
                        - arm64
                        - ppc64le
                        - s390x
                      - key: kubernetes.io/os
                        operator: In
                        values:
                        - linux
              containers:
              - args:
                - --secure-listen-address=0.0.0.0:8443
                - --upstream=http://127.0.0.1:8080/
                - --logtostderr=true
                - --v=0
                image: gcr.io/kubebuilder/kube-rbac-proxy:v0.13.0
                name: kube-rbac-proxy
                ports:
                - containerPort: 8443
                  name: https
                  protocol: TCP
                resources:
                  limits:
                    cpu: 500m
                    memory: 128Mi
                  requests:
                    cpu: 5m
                    memory: 64Mi
                securityContext:
                  allowPrivilegeEscalation: false
                  capabilities:
                    drop:
                    - ALL
              - args:
                - --health-probe-bind-address=:8081
                - --metrics-bind-address=127.0.0.1:8080
                - --leader-elect
                - --leader-election-id=stackgres-operator
                - --max-concurrent-reconciles=1
                - --reconcile-period=1000000h
                - --zap-devel
                image: registry.gitlab.com/ongresinc/stackgres/stackgres/stackgres-operator-helm:1.4.1
                livenessProbe:
                  httpGet:
                    path: /healthz
                    port: 8081
                  initialDelaySeconds: 15
                  periodSeconds: 20
                name: manager
                readinessProbe:
                  httpGet:
                    path: /readyz
                    port: 8081
                  initialDelaySeconds: 5
                  periodSeconds: 10
                resources:
                  limits:
                    cpu: 500m
                    memory: 128Mi
                  requests:
                    cpu: 10m
                    memory: 64Mi
                securityContext:
                  allowPrivilegeEscalation: false
                  capabilities:
                    drop:
                    - ALL
              initContainers:
              - command:
                - sh
                - -ec
                - |
                  kubectl get ns stackgres || kubectl create ns stackgres
                  cat << EOF | kubectl apply -n stackgres -f -
                  apiVersion: charts.stackgres.io/v1
                  kind: StackGresOperator
                  metadata:
                    name: stackgres-operator
                  spec: {}
                  EOF
                image: ongres/kubectl:v1.25.5-build-6.19
                name: default
                resources:
                  limits:
                    cpu: 500m
                    memory: 128Mi
                  requests:
                    cpu: 10m
                    memory: 64Mi
                securityContext:
                  allowPrivilegeEscalation: false
                  capabilities:
                    drop:
                    - ALL
                  runAsGroup: 1000
                  runAsNonRoot: true
                  runAsUser: 1000
              securityContext:
                runAsNonRoot: true
              serviceAccountName: stackgres-operator-controller-manager
              terminationGracePeriodSeconds: 10
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - coordination.k8s.io
          resources:
          - leases
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
          - patch
        serviceAccountName: stackgres-operator-controller-manager
    strategy: deployment
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - database-management
  - automation
  - postgresql
  links:
  - name: Stackgres Operator
    url: https://stackgres-operator.domain
  maintainers:
  - email: matteom@ongres.com
    name: Matteo Melli
  - email: gelias@ongres.com
    name: Guilherme Elias
  - email: jorsol@ongres.com
    name: Jorge Solorzano
  maturity: alpha
  provider:
    name: OnGres
    url: https://stackgres.io
  version: 1.4.1
