apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-cr-updater
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded