{{ if and (or (not .Values.cert.key) (not .Values.cert.crt)) ( or .Values.deploy.operator .Values.deploy.restapi ) }}
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}-create-certificate"
  namespace: {{ .Release.Namespace }}
  labels:
    app: "{{ .Release.Name }}-create-certificate"
    scope: init
    job: create-certificate
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
    "helm.sh/hook-weight": "0"
spec:
  template:
    metadata:
      labels:
        app: "{{ .Release.Name }}-create-certificate"
        scope: init
        job: create-certificate
    spec:
      serviceAccountName: {{ .Release.Name }}-init
      containers:
      - name: "{{ .Release.Name }}-create-certificate"
        image: "bitnami/kubectl:1.19.2"
        imagePullPolicy: "IfNotPresent"
        command:
          - "/bin/bash"
          - "-ecx"
          - |
            kubectl delete csr --ignore-not-found '{{ .Release.Name }}'
            cat << EOF > /tmp/csr.conf
            [req]
            req_extensions = v3_req
            distinguished_name = req_distinguished_name
            [req_distinguished_name]
            [ v3_req ]
            basicConstraints = CA:FALSE
            keyUsage = nonRepudiation, digitalSignature, keyEncipherment
            extendedKeyUsage = serverAuth
            subjectAltName = @alt_names
            [alt_names]
            DNS.1 = {{ .Release.Name }}
            DNS.2 = {{ .Release.Name }}.{{ .Release.Namespace }}
            DNS.3 = {{ .Release.Name }}.{{ .Release.Namespace }}.svc
            DNS.4 = {{ .Release.Name }}.{{ .Release.Namespace }}.svc.cluster.local
            EOF
            
            openssl req -new -nodes -text -keyout /tmp/root.key \
                -subj "/CN={{ .Release.Name }}.{{ .Release.Namespace }}.svc" \
                -out /tmp/server.csr \
                -config /tmp/csr.conf
            openssl rsa -in /tmp/root.key -pubout -out /tmp/root.pem
            
            cat << EOF | kubectl create -f -
            apiVersion: certificates.k8s.io/v1beta1
            kind: CertificateSigningRequest
            metadata:
              name: {{ .Release.Name }}
            spec:
              request: "$(cat /tmp/server.csr | base64 | tr -d '\n')"
              usages:
              - digital signature
              - key encipherment
              - server auth
            EOF
            
            if ! kubectl get csr '{{ .Release.Name }}' -o yaml|grep -q '^    type: Approved$'
            then
              {{- if .Values.cert.autoapprove }}
              kubectl certificate approve '{{ .Release.Name }}'
              {{- end }}
              echo -n "Waiting for CSR approval..."
              until kubectl get csr '{{ .Release.Name }}' -o yaml|grep -q '^    type: Approved$'
              do
                echo -n .
                sleep 5
              done
              echo "approved"
            fi
            echo -n "Waiting for CSR certificate generation..."
            until kubectl get csr '{{ .Release.Name }}' \
              --template '{{ "{{ if .status }}{{ if .status.certificate }}true{{ end }}{{ end }}" }}' \
              | grep -q '^true$'
            do
              echo -n .
              sleep 5
            done
            echo "certificate generated"

            KEY="$(cat /tmp/root.key | base64 | tr -d '\n')"
            PUB="$(cat /tmp/root.pem | base64 | tr -d '\n')"
            CRT="$(kubectl get csr '{{ .Release.Name }}' --template '{{ "{{ .status.certificate }}" }}')"
            
            if [ -z "$CRT" ]
            then
              echo "Certificate not found in CSR!"
              exit 1
            fi
            
            {{- $_ := set .Values.cert "crt" "${CRT}" }}
            {{- $_ := set .Values.cert "key" "${KEY}" }}
            {{- $_ := set .Values.cert "jwtRsaKey" "${KEY}" }}
            {{- $_ := set .Values.cert "jwtRsaPub" "${PUB}" }}
            cat << EOF > /tmp/validating-webhook-configuration.yaml
            {{- include (print $.Template.BasePath "/validating-webhook-configuration.yaml") . | indent 12 }}
            EOF
            cat << EOF > /tmp/mutating-webhook-configuration.yaml
            {{- include (print $.Template.BasePath "/mutating-webhook-configuration.yaml") . | indent 12 }}
            EOF
            cat << EOF > /tmp/certificate-secret.yaml
            {{- include (print $.Template.BasePath "/certificate-secret.yaml") . | indent 12 }}
            EOF
            {{- $_ := set .Values.cert "crt" nil }}
            {{- $_ := set .Values.cert "key" nil }}
            {{- $_ := set .Values.cert "jwtRsaKey" nil }}
            {{- $_ := set .Values.cert "jwtRsaPub" nil }}
            
            kubectl apply -f /tmp/validating-webhook-configuration.yaml
            kubectl apply -f /tmp/mutating-webhook-configuration.yaml
            kubectl apply -f /tmp/certificate-secret.yaml
      restartPolicy: OnFailure
{{ end }}
