{{- if and .Values.deploy.restapi .Values.authentication (not .Values.authentication.secretRef.name) }}
{{- if or (not .Release.IsUpgrade) (.Values.authentication.resetPassword) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.restapi.name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/managed-by: Helm
    api.stackgres.io/auth: user
type: Opaque
data:
  k8sUsername: {{ .Values.authentication.user | b64enc | quote }}
  password: {{ $password | b64enc | quote }}
  {{- if $clearPassword }}
  clearPassword: {{ $clearPassword | b64enc | quote }}
  {{- end }}
{{- end }}
{{- end }}
